# Generated by Django 6.0.1 on 2026-01-30 21:22

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='name',
            field=models.CharField(default='Unnamed Room', max_length=63),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=myapp.models.room_images_path, verbose_name='Image'),
        ),
    ]
