# Generated by Django 6.0.1 on 2026-01-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_images_image_rename_players_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
