# Generated by Django 6.0.1 on 2026-01-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='isPrivate',
            field=models.BooleanField(default=True),
        ),
    ]
