# Generated by Django 6.0.1 on 2026-01-31 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_room_isprivate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='isPrivate',
            new_name='isSearchable',
        ),
    ]
