# Generated by Django 6.0.2 on 2026-03-02 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_isprivate_room_issearchable'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomHitTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hit_target', to='myapp.room')),
            ],
        ),
    ]
